version: '3'
services:
  nginx:
    container_name: meridthio_nginx
    image: nginx
    ports:
      - "8080:80"

  flask:
    container_name: meridthio_flask
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
